# Generated by Django 4.0.3 on 2024-05-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmsApp', '0002_post_date_created_post_date_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
