# Generated by Django 4.0.3 on 2024-05-13 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fmsApp', '0003_trainingdates'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainingDates',
        ),
    ]
